parameters:
#    ez_disqus.example.class: BDunogier\EzDisqusBundle\Example

services:
#    ez_disqus.example:
#        class: %ez_disqus.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
